kitchen/urls.py
from django.urls import path

from kitchen import views

from django.contrib.auth import views as auth_views

from kitchen.views import (
    CookListView,
    KitchenInfoView,
    DishesView,
    DishCreateView,
    DishDeleteView,
    DishRemoveFromCookView,
    EditDishPriceView,
    IngredientsView,
    IngredientCreateView,
    IngredientDeleteView,
    IngredientDeleteInDishesView,
    CreateIngredientInDishesView,
    CookCreateView,
    CookDeleteView,
    AddDishToCookView
)

app_name = "kitchen"

urlpatterns = [
    path(
        "", views.home,
        name="home"
    ),
    path(
        "register/",
        views.register,
        name="register"
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout"
    ),
    path(
        "kitchen_info/",
        KitchenInfoView.as_view(),
        name="kitchen_info"
    ),
    path(
        "dishes/",
        DishesView.as_view(),
        name="dishes"
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dishes_create"
    ),
    path(
        "dishes/delete/<int:pk>/",
        DishDeleteView.as_view(),
        name="dish_delete"
    ),
    path(
        "dish/edit_price/<int:pk>/",
        EditDishPriceView.as_view(),
        name="edit_dish_price"
    ),
    path(
        "dishes/create_ingredient/<int:id>/",
        CreateIngredientInDishesView.as_view(),
        name="create_ingredient_in_dishes"
    ),
    path(
        "dish/remove/<int:dish_id>/from_cook/<int:cook_id>/",
        DishRemoveFromCookView.as_view(),
        name="dish_remove_from_cook"
    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cooks"
    ),
    path(
        "cooks/create/",
        CookCreateView.as_view(),
        name="cooks_create"
    ),
    path(
        "cooks/delete/<int:id>/",
        CookDeleteView.as_view(),
        name="cook_delete"
    ),
    path(
        "cook/<int:cook_id>/add_dish/",
        AddDishToCookView.as_view(),
        name="add_dish_to_cook"
    ),
    path(
        "ingredients/",
        IngredientsView.as_view(),
        name="ingredients"
    ),
    path(
        "ingredients/create/",
        IngredientCreateView.as_view(),
        name="ingredients_create"
    ),
    path(
        "ingredients/delete/in-dish<int:id>/",
        IngredientDeleteInDishesView.as_view(),
        name="ingredient_delete"
    ),
    path(
        "ingredients/delete/<int:ingredient_id>/",
        IngredientDeleteView.as_view(),
        name="delete_specific_ingredient"
    ),
]

kitchen_service/urls.py
from django.conf import settings


from django.conf.urls.static import static

from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

kitchen/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class DishType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = "dish type"
        verbose_name_plural = "dish types"

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(
        max_digits=5,
        decimal_places=2
    )
    ingredients = models.ManyToManyField(Ingredient)
    cooks = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="dishes"
    )
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

kitchen/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from kitchen.models import (
    Dish,
    Ingredient,
    Cook
)


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class":
                "form-control",
                "placeholder":
                "Username"
            }))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class":
                "form-control",
                "placeholder":
                    "Password"
            }))
    remember_me = (forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(),
        label="Remember Me"
    ))

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.add_input(
            Submit(
                "login",
                "Login",
                css_class="btn btn-primary"
            ))


class DishForm(forms.ModelForm):
    ingredients_text = forms.CharField(widget=forms.Textarea(attrs={
        "placeholder": "Write delicious ingredients for the dish please"}),
        label="Ingredients"
    )
    cooks_text = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Who will cook this dish?"}),
        label="Cooks"
    )
    description_text = forms.CharField(widget=forms.Textarea(attrs={
        "placeholder": "Describe the dish please"})
    )

    class Meta:
        model = Dish
        fields = [
            "name",
            "dish_type",
            "ingredients",
            "cooks_text",
            "description",
            "price"
        ]


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ["name"]


class CookForm(forms.ModelForm):
    class Meta:
        model = Cook
        fields = [
            "first_name",
            "last_name",
            "years_of_experience"
        ]

kitchen/views.py
from django.contrib import messages
from django.contrib.auth import (
    authenticate,
    login,
    get_user_model
)
from django.core.paginator import Paginator
from django.db.models import Value, CharField
from django.db.models.functions import Concat
from django.shortcuts import (
    redirect,
    render,
    get_object_or_404
)
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    ListView,
    CreateView,
    DeleteView,
    UpdateView
)

from kitchen.forms import (
    UserLoginForm,
    DishForm,
    IngredientForm,
    CookForm
)
from kitchen.models import (
    Dish,
    Cook,
    Ingredient
)


def home(request):
    if request.user.is_authenticated:
        return redirect("kitchen:kitchen_info")

    if request.method == "POST":
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if not form.cleaned_data.get("remember_me"):
                    request.session.set_expiry(0)
                return redirect("kitchen:kitchen_info")
            else:
                messages.error(
                    request,
                    "Invalid credentials. Please try again."
                )
        else:
            messages.error(
                request,
                "Form is not valid. Please try again."
            )
    else:
        form = UserLoginForm()

    return render(
        request,
        "kitchen/home.html",
        {"form": form}
    )


User = get_user_model()


def register(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        password2 = request.POST.get("password2")

        if password == password2:
            if not User.objects.filter(
                    username=username
            ).exists():
                user = User.objects.create_user(
                    username=username,
                    password=password
                )
                user.save()
                login(request, user)
                return redirect("kitchen:kitchen_info")
            else:
                return render(
                    request,
                    "kitchen/register.html",
                    {"error": "Username already exists"}
                )

    return render(request, "kitchen/register.html")


class KitchenInfoView(ListView):

    model = Dish
    template_name = "kitchen/kitchen_info.html"
    context_object_name = "Information_page"
    paginate_by = 12

    def get_queryset(self):
        return super().get_queryset().prefetch_related(
            "cooks",
            "ingredients",
            "dish_type"
        ).order_by("name")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = Paginator(self.get_queryset(), self.paginate_by)
        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context["Information_page"] = page_obj
        return context


class DishesView(ListView):

    model = Dish
    template_name = "kitchen/dishes.html"
    context_object_name = "dishes_page"
    paginate_by = 8

    def get_queryset(self):
        query = self.request.GET.get("dish_name")
        if query:
            return Dish.objects.filter(name__icontains=query).order_by("name")
        else:
            return Dish.objects.order_by("name")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.request.GET.get("dish_name")
        return context


class DishCreateView(CreateView):

    model = Dish
    form_class = DishForm
    template_name = "kitchen/dish_form.html"
    success_url = reverse_lazy("kitchen:dishes")


class DishDeleteView(DeleteView):

    model = Dish
    template_name = "kitchen/dishes.html"
    success_url = reverse_lazy("kitchen:dishes")


class DishRemoveFromCookView(View):

    def post(self, request, dish_id, cook_id):
        dish = get_object_or_404(Dish, id=dish_id)
        cook = get_object_or_404(Cook, id=cook_id)
        cook.dishes.remove(dish)
        return redirect("kitchen:cooks")

    def get(self, request, dish_id, cook_id):
        dish = get_object_or_404(Dish, id=dish_id)
        cook = get_object_or_404(Cook, id=cook_id)
        return render(
            request,
            "kitchen/dishes.html",
            {"dish": dish, "cook": cook}
        )


class EditDishPriceView(UpdateView):

    model = Dish
    template_name = "kitchen/edit_dish_price.html"
    fields = ["price"]
    success_url = reverse_lazy("kitchen:dishes")

    def form_valid(self, form):
        response = super().form_valid(form)
        return response


class IngredientsView(ListView):
    model = Ingredient
    template_name = "kitchen/ingredients.html"
    context_object_name = "ingredients_page"
    paginate_by = 24

    def get_queryset(self):
        query = self.request.GET.get("ingredient_name")
        if query:
            return Ingredient.objects.filter(
                name__icontains=query
            ).order_by("name")
        else:
            return Ingredient.objects.order_by("name")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.request.GET.get("ingredient_name")
        return context


class IngredientCreateView(CreateView):
    model = Ingredient
    form_class = IngredientForm
    template_name = "kitchen/create_ingredient.html"
    success_url = reverse_lazy("kitchen:ingredients")


class IngredientDeleteView(View):
    def post(self, request, *args, **kwargs):
        ingredient_id = kwargs.get("ingredient_id")
        ingredient = get_object_or_404(Ingredient, id=ingredient_id)
        ingredient.delete()
        return redirect("kitchen:ingredients")


class IngredientDeleteInDishesView(View):
    def post(self, request, *args, **kwargs):
        ingredient_id = kwargs.get("id")
        ingredient = get_object_or_404(Ingredient, id=ingredient_id)
        dishes = Dish.objects.filter(ingredients=ingredient)
        for dish in dishes:
            dish.ingredients.remove(ingredient)
        return redirect(request.META.get(
            "HTTP_REFERER",
            "redirect_if_referer_not_found")
        )

    def get(self, request, *args, **kwargs):
        ingredient_id = kwargs.get("id")
        ingredient = get_object_or_404(Ingredient, id=ingredient_id)
        return render(
            request,
            "kitchen/ingredients.html",
            {"ingredient": ingredient}
        )


class CreateIngredientInDishesView(View):
    def post(self, request, *args, **kwargs):
        dish_id = kwargs.get("id")
        dish = get_object_or_404(Dish, id=dish_id)
        form = IngredientForm(request.POST)
        if form.is_valid():
            ingredient = form.save()
            dish.ingredients.add(ingredient)
            return redirect("kitchen:dishes")
        return render(
            request,
            "kitchen/create_ingredient_in_dishes.html",
            {"form": form, "dish": dish}
        )

    def get(self, request, *args, **kwargs):
        dish_id = kwargs.get("id")
        dish = get_object_or_404(Dish, id=dish_id)
        form = IngredientForm()
        return render(
            request,
            "kitchen/create_ingredient_in_dishes.html",
            {"form": form, "dish": dish}
        )


class CookListView(ListView):
    model = Cook
    template_name = "kitchen/cooks.html"
    context_object_name = "cook_list"
    paginate_by = 8

    def get_queryset(self):
        full_name = self.request.GET.get("full_name")
        queryset = super().get_queryset()
        if full_name:
            queryset = queryset.annotate(
                full_name=Concat(
                    "first_name", Value(" "),
                    "last_name", output_field=CharField()
                )
            ).filter(full_name__icontains=full_name)
        return queryset.filter(
            years_of_experience__gt=0
        ).order_by("first_name")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.request.GET.get("full_name", "")
        return context


class CookCreateView(View):
    def post(self, request, *args, **kwargs):
        form = CookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("kitchen:cooks")
        return render(
            request,
            "kitchen/cook_form.html",
            {"form": form}
        )

    def get(self, request, *args, **kwargs):
        form = CookForm()
        return render(
            request,
            "kitchen/cook_form.html",
            {"form": form}
        )


class CookDeleteView(View):
    def post(self, request, *args, **kwargs):
        cook_id = kwargs.get("id")
        cook = get_object_or_404(Cook, id=cook_id)
        cook.delete()
        return redirect("kitchen:cooks")

    def get(self, request, *args, **kwargs):
        return render(request, "kitchen/cooks.html")


class AddDishToCookView(View):
    def post(self, request, *args, **kwargs):
        cook_id = kwargs.get("cook_id")
        cook = get_object_or_404(Cook, id=cook_id)
        form = DishForm(request.POST)
        if form.is_valid():
            dish = form.save()
            cook.dishes.add(dish)
            return redirect("kitchen:cooks")
        return render(
            request,
            "kitchen/add_dish_to_cook.html",
            {"form": form, "cook": cook}
        )

    def get(self, request, *args, **kwargs):
        cook_id = kwargs.get("cook_id")

templates/kitchen/add_dish_to_cook.html
{% extends 'base.html' %}

{% block content %}
<div class="add-dish-title-container">
    <div class="add-dish-header-buttons">
        <a href="javascript:history.back()" class="add-dish-btn-back"><i class="fas fa-arrow-left"></i> Back</a>
        <h1 class="add-dish-assigned-cooks-title">Add Dish to {{ cook.first_name }} {{ cook.last_name }}</h1>
    </div>
</div>

<div class="add-dish-content-container">
    <form method="post" class="add-dish-form">
        {% csrf_token %}
        <div class="add-dish-form-group">
            <label for="dish_name">Dish Name:</label>
            <input type="text" id="dish_name" name="dish_name" required class="add-dish-form-control">
        </div>
        <div class="add-dish-btn-container">
            <button type="submit" class="add-dish-btn-submit">Add Dish</button>
        </div>
    </form>
</div>
{% endblock %}

templates/kitchen/cook_form.html
{% extends 'base.html' %}

{% block content %}
<div class="create-cook-title-container">
    <div class="create-cook-header-buttons">
        <a href="javascript:history.back()" class="create-cook-btn-back"><i class="fas fa-arrow-left"></i> Back</a>
        <h1 class="create-cook-assigned-cooks-title">Add Cook</h1>
    </div>
</div>

<div class="create-cook-content-container">
    <form method="post" class="create-cook-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="create-cook-btn-submit">Add Cook</button>
    </form>
</div>
{% endblock %}

templates/kitchen/cooks.html
{% extends 'base.html' %}

{% block content %}
<div class="title-container">
    <div class="header-buttons">
        <a href="javascript:history.back()" class="btn-back"><i class="fas fa-arrow-left"></i> Back</a>
        <h1 class="assigned-cooks-title">Cooks</h1>
        <form method="get" action="{% url 'kitchen:cooks' %}" class="search-form">
            <input type="text" name="full_name" placeholder="Search cooks" value="{{ query|default_if_none:'' }}">
            <button type="submit">Search</button>
        </form>
        <a href="{% url 'kitchen:cooks_create' %}" class="btn-create">Add Cook</a>
    </div>
</div>

<div class="cooks-container">
    <ul class="cook-list">
        {% for cook in page_obj %}
            <li class="cook-item">
                <form method="post" action="{% url 'kitchen:cook_delete' cook.id %}" class="delete-form">
                    {% csrf_token %}
                    <button type="submit" class="btn-delete">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </form>
                <h2 class="cook-name">{{ cook.first_name }} {{ cook.last_name }}</h2>
                <p class="cook-experience">{{ cook.years_of_experience }} years of experience</p>
                <ul class="dishes-list">
                    {% for dish in cook.dishes.all %}
                        <li>
                            <div class="cooks-dish-item-container">
                                <h3 class="dish-name">{{ dish.name }}</h3>
                                <form method="post" action="{% url 'kitchen:dish_remove_from_cook' dish.id cook.id %}" class="dish-delete-form">
                                    {% csrf_token %}
                                    <input type="hidden" name="cook_id" value="{{ cook.id }}">
                                    <button type="submit" class="btn-dish-delete">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </form>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <a href="{% url 'kitchen:add_dish_to_cook' cook.id %}" class="btn-add-dish">Add Dish</a>
            </li>
        {% endfor %}
    </ul>
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">&raquo; last</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/kitchen/create_ingredient.html
{% extends 'base.html' %}

{% block content %}
<div class="create-dish-title-container">
    <h1 class="create-dish-title">Create New Dish</h1>
</div>

<div class="create-dish-auth-container">
    <div class="create-dish-auth-box">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.name.label_tag }}
                {{ form.name }}
            </div>
            <div class="form-group">
                {{ form.description.label_tag }}
                {{ form.description }}
            </div>
            <div class="form-group">
                {{ form.price.label_tag }}
                {{ form.price }}
            </div>
            <div class="form-group">
                {{ form.dish_type.label_tag }}
                {{ form.dish_type }}
            </div>
            <div class="form-group">
                {{ form.ingredients_text.label_tag }}
                {{ form.ingredients_text }}
            </div>
            <div class="form-group">
                {{ form.cooks_text.label_tag }}
                {{ form.cooks_text }}
            </div>
            <button type="submit" class="create-dish-btn-submit">
                <i class=></i> Add ingredient
            </button>
        </form>
    </div>
</div>
{% endblock %}

templates/kitchen/create_ingredient_in_dishes.html
{% extends 'base.html' %}

{% block content %}
<div class="create-ingredient-title-container">
    <div class="create-ingredient-header-buttons">
        <a href="javascript:history.back()" class="create-ingredient-btn-back"><i class="fas fa-arrow-left"></i> Back</a>
        <h1 class="create-ingredient-assigned-cooks-title">Add Ingredient to {{ dish.name }}</h1>
    </div>
</div>

<div class="create-ingredient-content-container">
    <form method="post" class="create-ingredient-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="create-ingredient-btn-submit">Add Ingredient</button>
    </form>
</div>
{% endblock %}

templates/kitchen/dishes.html
{% extends 'base.html' %}

{% block content %}
<div class="title-container">
    <div class="header-buttons">
        <a href="javascript:history.back()" class="btn-back"><i class="fas fa-arrow-left"></i> Back</a>
        <h1 class="assigned-cooks-title">Dishes</h1>
        <form method="GET" action="{% url 'kitchen:dishes' %}" class="search-form">
            <input type="text" name="dish_name" placeholder="Search dishes..." value="{{ request.GET.dish_name }}">
            <button type="submit">Search</button>
        </form>
        <a href="{% url 'kitchen:dishes_create' %}" class="btn-create">Create Dish</a>
    </div>
</div>

<div class="dishes-container">
    <ul class="dish-list">
        {% for dish in dishes_page %}
            <li class="dish-item">
                <form method="post" action="{% url 'kitchen:dish_delete' dish.pk %}" class="delete-form">
                    {% csrf_token %}
                    <button type="submit" class="btn-delete">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </form>
                <h2 class="dish-name">{{ dish.name }}</h2>
                <p class="dish-type">{{ dish.dish_type }}</p>
                <p class="dish-description">{{ dish.description }}</p>
                <a href="{% url 'kitchen:create_ingredient_in_dishes' dish.id %}" class="btn-add-ingredient btn-move-lower">
                    <i class="fas fa-plus"></i>
                </a>
                <ul class="ingredients-list">
                    {% for ingredient in dish.ingredients.all %}
                        <li class="ingredient-item">
                            <span>{{ ingredient }}</span>
                            <form method="post" action="{% url 'kitchen:ingredient_delete' ingredient.id %}" class="ingredient-delete-form">
                                {% csrf_token %}
                                <button type="submit" class="btn-ingredient-delete">
                                    <i class="fas fa-times"></i>
                                </button>
                            </form>
                        </li>
                    {% endfor %}
                </ul>
                <div class="price-container">
                    <a href="{% url 'kitchen:edit_dish_price' dish.pk %}" class="btn-edit-price">
                        <i class="fas fa-pencil-alt"></i>
                    </a>
                    <p class="dish-price"><strong>Price:</strong> ${{ dish.price }}</p>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">&raquo; last</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/kitchen/edit_dish_price.html
{% extends 'base.html' %}

{% block content %}
<div class="edit-dish-title-container">
    <div class="edit-dish-header-buttons">
        <a href="javascript:history.back()" class="edit-dish-btn-back"><i class="fas fa-arrow-left"></i> Back</a>
        <h1 class="edit-dish-assigned-cooks-title">Edit Dish Price</h1>
    </div>
</div>

<div class="edit-dish-price-container">
    <form method="post" action="{% url 'kitchen:edit_dish_price' dish.id %}">
        {% csrf_token %}
        <div class="edit-dish-form-group">
            <label for="dish-name">Dish Name:</label>
            <input type="text" id="dish-name" name="dish_name" value="{{ dish.name }}" disabled>
        </div>
        <div class="edit-dish-form-group">
            <label for="dish-price">Price:</label>
            <input type="number" id="dish-price" name="dish_price" value="{{ dish.price }}" step="0.01">
        </div>
        <div class="edit-dish-form-buttons">
            <button type="submit" class="edit-dish-btn-update">Update</button>
            <a href="javascript:history.back()" class="edit-dish-btn-cancel">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

templates/kitchen/home.html
{% extends 'base.html' %}

{% block content %}
<div class="auth-container">
   <div class="auth-box">
       <div class="logo no-hover">
           <i class="fas fa-utensils"></i>
           <h1>Kitchen Service</h1>
       </div>

       <form method="post" action="{% url 'kitchen:home' %}">
           {% csrf_token %}
           <div class="form-group">
               <label for="{{ form.username.id_for_label }}">Username</label>
               {{ form.username }}
           </div>
           <div class="form-group">
               <label for="{{ form.password.id_for_label }}">Password</label>
               {{ form.password }}
           </div>

           <div class="remember-me">
               {{ form.remember_me }}
               <label for="{{ form.remember_me.id_for_label }}">Remember Me</label>
           </div>

           <button type="submit" class="btn btn-primary btn-small">
               <i class="fas fa-sign-in-alt"></i>
               Enter
           </button>
       </form>

       <div class="auth-links">
           <a href="{% url 'kitchen:register' %}" class="btn btn-secondary btn-small">
               <i class="fas fa-user-plus"></i>
               Register
           </a>
       </div>
   </div>
</div>
{% endblock %}

templates/kitchen/ingredients.html
{% extends 'base.html' %}

{% block content %}
<div class="title-container">
    <div class="header-buttons">
        <a href="javascript:history.back()" class="btn-back"><i class="fas fa-arrow-left"></i> Back</a>
        <h1 class="assigned-cooks-title">Ingredients</h1>
        <form method="get" action="{% url 'kitchen:ingredients' %}" class="search-form">
            <input type="text" name="ingredient_name" placeholder="Search ingredients" value="{{ query|default_if_none:'' }}">
            <button type="submit">Search</button>
        </form>
        <a href="{% url 'kitchen:ingredients_create' %}" class="btn-create">Add Ingredient</a>
    </div>
</div>

<div class="ingredient-specific-container">
    <div class="ingredient-specific-box">
        <ul class="ingredient-specific-list">
            {% for ingredient in page_obj %}
                <li class="ingredient-specific-item">
                    <form method="post" action="{% url 'kitchen:delete_specific_ingredient' ingredient.id %}" class="ingredient-specific-delete-form">
                        {% csrf_token %}
                        <button type="submit" class="ingredient-specific-btn-delete">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </form>
                    {{ ingredient.name }}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">&raquo; last</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/kitchen/register.html
{% extends 'base.html' %}


{% block content %}
 <div class="auth-container">
   <div class="auth-box">
       <form method="post">
           {% csrf_token %}
           {% if error %}
               <p style="color: red;">{{ error }}</p>
           {% endif %}
           <div class="form-group">
               <label for="id_username">Username:</label>
               <input type="text" name="username" id="id_username" required class="form-control">
           </div>
           <div class="form-group">
               <label for="id_password">Password:</label>
               <input type="password" name="password" id="id_password" required class="form-control">
           </div>
           <div class="form-group">
               <label for="id_password2">Confirm Password:</label>
               <input type="password" name="password2" id="id_password2" required class="form-control">
           </div>
           <button type="submit" class="btn btn-primary">Register</button>
       </form>
   </div>
</div>
{% endblock %}